version: "3"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./database/:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "auth"
    ports:
      - "5432:5432"

  auth_mc:
    build: .
    container_name: auth_mc
    depends_on:
      - db
      - kafka
#    restart: always
    command:
      - go test ./tests
    environment:
      - CONFIG_PATH=./config/dev.yaml
    ports:
      - "8002:44044"

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    ports:
      - "2181:8080"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper